export const BRAND = 'DoctPrint'

export const categories = [
  { id: 'printer', label: 'Printer', icon: 'print' },
  { id: 'tinta', label: 'Tinta & Toner', icon: 'ink_pen' },
  { id: 'kertas', label: 'Kertas', icon: 'description' },
  { id: 'aksesori', label: 'Aksesori', icon: 'mouse' },
]

export const products = [
  {
    id: 'printer-ecotank-l3110',
    name: 'Printer Epson EcoTank L3110',
    unit: '/unit',
    price: 2700000,
    oldPrice: null,
    rating: 4.9,
    badge: 'Terlaris',
    desc: 'Printer multifungsi print-scan-copy dengan teknologi EcoTank yang hemat tinta. Kapasitas tangki besar, cocok untuk kebutuhan cetak harian kantor maupun rumahan.',
    specs: [
      { icon: 'print', label: 'Print-Scan-Copy' },
      { icon: 'savings', label: 'Hemat Tinta' },
      { icon: 'bolt', label: 'Cetak Cepat' },
      { icon: 'verified_user', label: 'Garansi 1 Tahun' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#0f172a' },
      { label: 'Putih', hex: '#ffffff' },
    ],
    paperOptions: ['Single Function', 'Multi Function'],
  },
  {
    id: 'printer-canon-ip2770',
    name: 'Printer Canon PIXMA iP2770',
    unit: '/unit',
    price: 850000,
    oldPrice: null,
    rating: 4.7,
    badge: null,
    desc: 'Printer inkjet praktis untuk cetak dokumen dan foto. Ringkas, ringan, dan mudah digunakan dengan hasil cetak tajam.',
    specs: [
      { icon: 'print', label: 'Cetak Dokumen' },
      { icon: 'straighten', label: 'Desain Ringkas' },
      { icon: 'bolt', label: 'Instalasi Mudah' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#0f172a' }],
    paperOptions: ['Tinta Hitam', 'Tinta Warna'],
  },
  {
    id: 'cartridge-canon-pg-47',
    name: 'Cartridge Canon PG-47 (Hitam)',
    unit: '/pcs',
    price: 185000,
    oldPrice: 210000,
    rating: 4.8,
    badge: 'Sale',
    desc: 'Cartridge asli Canon untuk hasil cetak hitam pekat dan awet. Kompatibel dengan printer PIXMA iP2770 dan seri sejenis.',
    specs: [
      { icon: 'verified', label: 'Original' },
      { icon: 'ink_pen', label: 'Hitam Pekat' },
      { icon: 'savings', label: 'Harga Terjangkau' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#111827' },
      { label: 'Warna', hex: '#f97316' },
    ],
    paperOptions: ['Original', 'Compatible'],
  },
  {
    id: 'toner-hp-85a',
    name: 'Toner HP 85A (CE285A)',
    unit: '/pcs',
    price: 320000,
    oldPrice: null,
    rating: 4.8,
    badge: 'Baru',
    desc: 'Toner original HP untuk hasil cetak bersih dan konsisten. Cocok untuk printer HP LaserJet P1102, M1132, dan sejenisnya.',
    specs: [
      { icon: 'verified', label: 'Original HP' },
      { icon: 'high_quality', label: 'Hasil Tajam' },
      { icon: 'archive', label: 'Dayai Tahan Lama' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['Standard', 'High Yield'],
  },
  {
    id: 'kertas-a4-80gsm',
    name: 'Kertas A4 80gsm',
    unit: '/rim',
    price: 55000,
    oldPrice: 62000,
    rating: 4.7,
    badge: 'Promo',
    desc: 'Kertas HVS A4 premium 80gsm, putih bersih dan halus. Cocok untuk dokumen kantor, tugas, dan keperluan cetak sehari-hari.',
    specs: [
      { icon: 'description', label: 'Ukuran A4' },
      { icon: 'layers', label: '80gsm Tebal' },
      { icon: 'savings', label: 'Hemat' },
    ],
    colorOptions: [{ label: 'Putih', hex: '#ffffff' }],
    paperOptions: ['70gsm', '80gsm'],
  },
  {
    id: 'mouse-logitech-m170',
    name: 'Mouse Wireless Logitech M170',
    unit: '/unit',
    price: 139000,
    oldPrice: null,
    rating: 4.6,
    badge: null,
    desc: 'Mouse wireless nirkabel yang nyaman digenggam. Koneksi stabil, baterai tahan lama hingga 12 bulan, plug-and-play tanpa driver.',
    specs: [
      { icon: 'wifi', label: 'Nirkabel' },
      { icon: 'handshake', label: 'Ergonomis' },
      { icon: 'battery_full', label: 'Baterai Tahan Lama' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#111827' },
      { label: 'Abu', hex: '#cbd5e1' },
    ],
    paperOptions: ['Wired', 'Wireless'],
  },
  {
    id: 'keyboard-usb-standard',
    name: 'Keyboard USB Standard',
    unit: '/unit',
    price: 75000,
    oldPrice: null,
    rating: 4.5,
    badge: null,
    desc: 'Keyboard USB standar dengan tombol nyaman dan awet. Plug-and-play, kompatibel dengan Windows, macOS, dan Linux.',
    specs: [
      { icon: 'keyboard', label: 'Full Size' },
      { icon: 'bolt', label: 'Plug & Play' },
      { icon: 'shield', label: 'Tahan Lama' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['USB Wired', 'Wireless'],
  },
  {
    id: 'flashdisk-kingston-32gb',
    name: 'Flashdisk Kingston 32GB',
    unit: '/unit',
    price: 115000,
    oldPrice: null,
    rating: 4.9,
    badge: null,
    desc: 'Flashdisk Kingston kapasitas 32GB dengan transfer data cepat. Body kokoh, cocok untuk menyimpan dan memindahkan file kerja.',
    specs: [
      { icon: 'speed', label: 'Transfer Cepat' },
      { icon: 'storage', label: 'Kapasitas 32GB' },
      { icon: 'shield', label: 'Body Kokoh' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['USB 2.0', 'USB 3.0'],
  },
]

export const profileMenu = [
  { label: 'Pesanan Saya', icon: 'receipt_long' },
  { label: 'Metode Pembayaran', icon: 'credit_card' },
  { label: 'Alamat Pengiriman', icon: 'location_on' },
  { label: 'Keamanan & Sandi', icon: 'lock' },
  { label: 'Pengaturan Notifikasi', icon: 'notifications' },
  { label: 'Pusat Bantuan', icon: 'help' },
]