export const BRAND = 'DoctPrint'

export const categories = [
  { id: 'printer', label: 'Printer', icon: 'print' },
  { id: 'tinta', label: 'Tinta & Toner', icon: 'ink_pen' },
  { id: 'kertas', label: 'Kertas', icon: 'description' },
  { id: 'aksesori', label: 'Aksesori', icon: 'mouse' },
]

export const products = [
  {
    id: 'printer-ecotank-l3110',
    categoryId: 'printer',
    name: 'Printer Epson EcoTank L3110',
    unit: '/unit',
    price: 2700000,
    oldPrice: null,
    rating: 4.9,
    sold: 215,
    stock: 12,
    badge: 'Terlaris',
    video: 'https://www.youtube.com/watch?v=7_-NXb3sNEo',
    desc: 'Printer multifungsi print-scan-copy dengan teknologi EcoTank yang hemat tinta. Kapasitas tangki besar, cocok untuk kebutuhan cetak harian kantor maupun rumahan.',
    specs: [
      { icon: 'print', label: 'Print-Scan-Copy' },
      { icon: 'savings', label: 'Hemat Tinta' },
      { icon: 'bolt', label: 'Cetak Cepat' },
      { icon: 'verified_user', label: 'Garansi 1 Tahun' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#0f172a' },
      { label: 'Putih', hex: '#ffffff' },
    ],
    paperOptions: ['Single Function', 'Multi Function'],
    reviews: [
      { name: 'Andi Wijaya', rating: 5, date: '12 Jul 2026', comment: 'Hemat tinta dan hasil cetak tajam. Sangat cocok untuk kebutuhan kantor harian.' },
      { name: 'Siti Rahma', rating: 5, date: '28 Jun 2026', comment: 'Instalasi mudah, koneksi cepat. Rekomendasi untuk print-scan-copy.' },
      { name: 'Rudi Hartono', rating: 4, date: '02 Jun 2026', comment: 'Bagus, hanya butuh penyesuaian awal untuk warna. Selebihnya oke.' },
    ],
  },
  {
    id: 'printer-canon-ip2770',
    categoryId: 'printer',
    name: 'Printer Canon PIXMA iP2770',
    unit: '/unit',
    price: 850000,
    oldPrice: null,
    rating: 4.7,
    sold: 148,
    stock: 7,
    badge: null,
    desc: 'Printer inkjet praktis untuk cetak dokumen dan foto. Ringkas, ringan, dan mudah digunakan dengan hasil cetak tajam.',
    specs: [
      { icon: 'print', label: 'Cetak Dokumen' },
      { icon: 'straighten', label: 'Desain Ringkas' },
      { icon: 'bolt', label: 'Instalasi Mudah' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#0f172a' }],
    paperOptions: ['Tinta Hitam', 'Tinta Warna'],
  },
  {
    id: 'cartridge-canon-pg-47',
    categoryId: 'tinta',
    name: 'Cartridge Canon PG-47 (Hitam)',
    unit: '/pcs',
    price: 185000,
    oldPrice: 210000,
    rating: 4.8,
    sold: 320,
    stock: 25,
    badge: 'Sale',
    desc: 'Cartridge asli Canon untuk hasil cetak hitam pekat dan awet. Kompatibel dengan printer PIXMA iP2770 dan seri sejenis.',
    specs: [
      { icon: 'verified', label: 'Original' },
      { icon: 'ink_pen', label: 'Hitam Pekat' },
      { icon: 'savings', label: 'Harga Terjangkau' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#111827' },
      { label: 'Warna', hex: '#f97316' },
    ],
    paperOptions: ['Original', 'Compatible'],
    reviews: [
      { name: 'Dewi Lestari', rating: 5, date: '18 Jul 2026', comment: 'Cartridge original, hasil cetak hitam pekat dan awet.' },
      { name: 'Bambang Pamungkas', rating: 4, date: '30 Jun 2026', comment: 'Harga lebih murah dari toko lain, kualitas terjamin.' },
    ],
  },
  {
    id: 'toner-hp-85a',
    categoryId: 'tinta',
    name: 'Toner HP 85A (CE285A)',
    unit: '/pcs',
    price: 320000,
    oldPrice: null,
    rating: 4.8,
    sold: 190,
    stock: 4,
    badge: 'Baru',
    desc: 'Toner original HP untuk hasil cetak bersih dan konsisten. Cocok untuk printer HP LaserJet P1102, M1132, dan sejenisnya.',
    specs: [
      { icon: 'verified', label: 'Original HP' },
      { icon: 'high_quality', label: 'Hasil Tajam' },
      { icon: 'archive', label: 'Dayai Tahan Lama' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['Standard', 'High Yield'],
  },
  {
    id: 'kertas-a4-80gsm',
    categoryId: 'kertas',
    name: 'Kertas A4 80gsm',
    unit: '/rim',
    price: 55000,
    oldPrice: 62000,
    rating: 4.7,
    sold: 540,
    stock: 60,
    badge: 'Promo',
    desc: 'Kertas HVS A4 premium 80gsm, putih bersih dan halus. Cocok untuk dokumen kantor, tugas, dan keperluan cetak sehari-hari.',
    specs: [
      { icon: 'description', label: 'Ukuran A4' },
      { icon: 'layers', label: '80gsm Tebal' },
      { icon: 'savings', label: 'Hemat' },
    ],
    colorOptions: [{ label: 'Putih', hex: '#ffffff' }],
    paperOptions: ['70gsm', '80gsm'],
    reviews: [
      { name: 'Nur Aini', rating: 5, date: '20 Jul 2026', comment: 'Kertas tebal dan putih bersih, cocok untuk dokumen penting.' },
      { name: 'Fajar Nugroho', rating: 4, date: '11 Jul 2026', comment: 'Bagus, pengiriman cepat. Kertas tidak mudah lengket.' },
    ],
  },
  {
    id: 'mouse-logitech-m170',
    categoryId: 'aksesori',
    name: 'Mouse Wireless Logitech M170',
    unit: '/unit',
    price: 139000,
    oldPrice: null,
    rating: 4.6,
    sold: 260,
    stock: 3,
    badge: null,
    desc: 'Mouse wireless nirkabel yang nyaman digenggam. Koneksi stabil, baterai tahan lama hingga 12 bulan, plug-and-play tanpa driver.',
    specs: [
      { icon: 'wifi', label: 'Nirkabel' },
      { icon: 'handshake', label: 'Ergonomis' },
      { icon: 'battery_full', label: 'Baterai Tahan Lama' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#111827' },
      { label: 'Abu', hex: '#cbd5e1' },
    ],
    paperOptions: ['Wired', 'Wireless'],
    reviews: [
      { name: 'Rina Kusuma', rating: 5, date: '15 Jul 2026', comment: 'Ringan dan nyaman, baterai benar-benar awet.' },
      { name: 'Agus Salim', rating: 4, date: '05 Jul 2026', comment: 'Koneksi stabil, plug and play. Cocok untuk kerja harian.' },
    ],
  },
  {
    id: 'keyboard-usb-standard',
    categoryId: 'aksesori',
    name: 'Keyboard USB Standard',
    unit: '/unit',
    price: 75000,
    oldPrice: null,
    rating: 4.5,
    sold: 180,
    stock: 0,
    badge: null,
    desc: 'Keyboard USB standar dengan tombol nyaman dan awet. Plug-and-play, kompatibel dengan Windows, macOS, dan Linux.',
    specs: [
      { icon: 'keyboard', label: 'Full Size' },
      { icon: 'bolt', label: 'Plug & Play' },
      { icon: 'shield', label: 'Tahan Lama' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['USB Wired', 'Wireless'],
  },
  {
    id: 'flashdisk-kingston-32gb',
    categoryId: 'aksesori',
    name: 'Flashdisk Kingston 32GB',
    unit: '/unit',
    price: 115000,
    oldPrice: null,
    rating: 4.9,
    sold: 220,
    stock: 15,
    badge: null,
    desc: 'Flashdisk Kingston kapasitas 32GB dengan transfer data cepat. Body kokoh, cocok untuk menyimpan dan memindahkan file kerja.',
    specs: [
      { icon: 'speed', label: 'Transfer Cepat' },
      { icon: 'storage', label: 'Kapasitas 32GB' },
      { icon: 'shield', label: 'Body Kokoh' },
    ],
    colorOptions: [{ label: 'Hitam', hex: '#111827' }],
    paperOptions: ['USB 2.0', 'USB 3.0'],
  },
]

export const profileMenu = [
  { label: 'Pesanan Saya', icon: 'receipt_long' },
  { label: 'Metode Pembayaran', icon: 'credit_card' },
  { label: 'Alamat Pengiriman', icon: 'location_on' },
  { label: 'Keamanan & Sandi', icon: 'lock' },
  { label: 'Pengaturan Notifikasi', icon: 'notifications' },
  { label: 'Pusat Bantuan', icon: 'help' },
]

export const heroSlides = [
  {
    eyebrow: 'Promo Spesial',
    title: 'Diskon Alat Kantor 20%',
    desc: 'Printer, tinta, toner, kertas, dan aksesori kantor dengan harga bersahabat.',
    cta: 'Pesan Sekarang',
    href: '#/cart',
    bg: 'linear-gradient(120deg, #0f172a 0%, #1e293b 50%, #f97316 125%)',
  },
  {
    eyebrow: 'Koleksi Printer',
    title: 'Printer Terbaik untuk Kantor Anda',
    desc: 'EcoTank hemat tinta, PIXMA serbaguna, hingga kebutuhan cetak harian lainnya.',
    cta: 'Lihat Produk',
    href: '#/product?id=printer-ecotank-l3110',
    bg: 'linear-gradient(120deg, #f97316 0%, #fd761a 55%, #ea580c 110%)',
  },
  {
    eyebrow: 'Tinta & Toner Original',
    title: 'Hasil Cetak Selalu Tajam',
    desc: 'Cartridge dan toner original untuk performa terbaik setiap printer Anda.',
    cta: 'Belanja Sekarang',
    href: '#/product?id=toner-hp-85a',
    bg: 'linear-gradient(120deg, #131b2e 0%, #0f172a 100%)',
  },
]

export const shippingOptions = [
  { id: 'standard', label: 'Pengiriman Standar', desc: '3-5 Hari Kerja', price: 0 },
  { id: 'express', label: 'Pengiriman Ekspres', desc: '1-2 Hari Kerja', price: 15000 },
]

export const provinces = ['Jawa Barat', 'DKI Jakarta', 'Jawa Timur']

export const user = {
  name: 'Budi Santoso',
  email: 'budi.santoso@email.com',
  stats: [
    { icon: 'local_shipping', value: '2', label: 'Pesanan Aktif' },
    { icon: 'favorite', value: '14', label: 'Wishlist' },
    { icon: 'confirmation_number', value: '5', label: 'Kupon' },
  ],
}