export const BRAND = 'DoctPrint'

export const categories = [
  { id: 'dokumen', label: 'Dokumen', icon: 'description' },
  { id: 'foto', label: 'Foto', icon: 'photo_camera' },
  { id: 'jilid', label: 'Jilid', icon: 'menu_book' },
  { id: 'merch', label: 'Merch', icon: 'checkroom' },
]

export const products = [
  {
    id: 'cetak-fullcolor',
    name: 'Cetak Dokumen Full Color',
    unit: '/lembar',
    price: 2000,
    oldPrice: null,
    rating: 4.8,
    badge: null,
    desc: 'Cetak dokumen dengan kualitas warna tajam dan resolusi tinggi. Cocok untuk proposal, brosur, hingga materi presentasi. Harga per lembar, minimal 1 lembar.',
    specs: [
      { icon: 'high_quality', label: 'Kualitas HD' },
      { icon: 'bolt', label: 'Cetak Cepat' },
      { icon: 'palette', label: 'Warna Akurat' },
      { icon: 'savings', label: 'Harga Bersahabat' },
    ],
    colorOptions: [
      { label: 'Putih', hex: '#ffffff' },
      { label: 'Krem', hex: '#f5f0e1' },
      { label: 'Abu', hex: '#cbd5e1' },
    ],
    paperOptions: ['HVS 80gsm', 'HVS 100gsm', 'Art Paper'],
  },
  {
    id: 'cetak-foto',
    name: 'Cetak Foto Glossy 4R',
    unit: '/lembar',
    price: 3500,
    oldPrice: null,
    rating: 4.9,
    badge: 'Baru',
    desc: 'Cetak foto memakai kertas glossy dan tinta warna berkualitas tinggi, warna hidup dan tahan lama.',
    specs: [
      { icon: 'photo_camera', label: 'Warna Hidup' },
      { icon: 'layers', label: 'Finish Glossy' },
    ],
    colorOptions: [{ label: 'Glossy', hex: '#e2e8f0' }],
    paperOptions: ['Glossy 4R', 'Lustre 4R'],
  },
  {
    id: 'jilid-skripsi',
    name: 'Jilid Skripsi Hard Cover',
    unit: '/eksemplar',
    price: 25000,
    oldPrice: null,
    rating: 4.7,
    badge: null,
    desc: 'Jilid hard cover dengan karton tebal dan laminasi mengkilap, rapi dan kokoh untuk dokumen tugas akhir.',
    specs: [
      { icon: 'menu_book', label: 'Hard Cover' },
      { icon: 'check_circle', label: 'Hasil Rapi' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#0f172a' },
      { label: 'Navy', hex: '#1e293b' },
    ],
    paperOptions: ['Hard Cover', 'Soft Cover'],
  },
  {
    id: 'fotokopi-hp',
    name: 'Fotokopi Hitam Putih',
    unit: '/lembar',
    price: 250,
    oldPrice: 350,
    rating: 4.6,
    badge: 'Sale',
    desc: 'Fotokopi cepat hitam putih untuk dokumen harian, hasil bersih dan tajam dengan harga murah.',
    specs: [
      { icon: 'content_copy', label: 'Hasil Bersih' },
      { icon: 'rocket_launch', label: 'Proses Kilat' },
    ],
    colorOptions: [{ label: 'HVS', hex: '#ffffff' }],
    paperOptions: ['A4', 'A5', 'F4'],
  },
  {
    id: 'cetak-kaos',
    name: 'Cetak Kaos Custom',
    unit: '/pcs',
    price: 85000,
    oldPrice: null,
    rating: 4.9,
    badge: null,
    desc: 'Cetak kaos custom dengan teknik sablon atau DTG, warna tajam dan awet digunakan.',
    specs: [
      { icon: 'checkroom', label: 'Sablon / DTG' },
      { icon: 'star', label: 'Awet' },
    ],
    colorOptions: [
      { label: 'Hitam', hex: '#0f172a' },
      { label: 'Putih', hex: '#ffffff' },
    ],
    paperOptions: ['Sablon', 'DTG'],
  },
  {
    id: 'banner',
    name: 'Banner & Spanduk',
    unit: '/m²',
    price: 45000,
    oldPrice: null,
    rating: 4.5,
    badge: null,
    desc: 'Cetak banner dan spanduk ukuran besar dengan bahan flexi dan potongan yang presisi.',
    specs: [
      { icon: 'flag', label: 'Bahan Flexi' },
      { icon: 'straighten', label: 'Potongan Presisi' },
    ],
    colorOptions: [{ label: 'Flexi', hex: '#e2e8f0' }],
    paperOptions: ['Flexi 280gsm', 'Flexi 340gsm'],
  },
  {
    id: 'kartu-nama',
    name: 'Cetak Kartu Nama',
    unit: '/box',
    price: 15000,
    oldPrice: null,
    rating: 4.8,
    badge: 'Promo',
    desc: 'Kartu nama glossy premium, potongan presisi, dan finishing laminasi.',
    specs: [
      { icon: 'credit_card', label: 'Finish Glossy' },
      { icon: 'content_cut', label: 'Potongan Presisi' },
    ],
    colorOptions: [{ label: 'Glossy', hex: '#e2e8f0' }],
    paperOptions: ['Art Paper 260', 'Art Paper 310'],
  },
  {
    id: 'stiker',
    name: 'Stiker & Label Custom',
    unit: '/lembar',
    price: 5000,
    oldPrice: null,
    rating: 4.7,
    badge: null,
    desc: 'Cetak stiker vinyl, doff, atau transparan sesuai kebutuhan branding Anda.',
    specs: [
      { icon: 'sell', label: 'Bahan Vinyl' },
      { icon: 'palette', label: 'Bentuk Custom' },
    ],
    colorOptions: [
      { label: 'Vinyl', hex: '#ffffff' },
      { label: 'Doff', hex: '#f1f5f9' },
    ],
    paperOptions: ['Vinyl', 'Doff', 'Transparan'],
  },
]

export const profileMenu = [
  { label: 'Pesanan Saya', icon: 'receipt_long' },
  { label: 'Metode Pembayaran', icon: 'credit_card' },
  { label: 'Alamat Pengiriman', icon: 'location_on' },
  { label: 'Keamanan & Sandi', icon: 'lock' },
  { label: 'Pengaturan Notifikasi', icon: 'notifications' },
  { label: 'Pusat Bantuan', icon: 'help' },
]